---
services:
  db:
    image: 919484653118.dkr.ecr.ap-southeast-2.amazonaws.com/pythonapp:database
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: 919484653118.dkr.ecr.ap-southeast-2.amazonaws.com/pythonapp:auth
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db

  book_service:
    image: 919484653118.dkr.ecr.ap-southeast-2.amazonaws.com/pythonapp:book
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow_service:
    image: 919484653118.dkr.ecr.ap-southeast-2.amazonaws.com/pythonapp:borrow
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: 919484653118.dkr.ecr.ap-southeast-2.amazonaws.com/pythonapp:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth_service
      - book_service
      - borrow_service

networks:
  mynetwork:
    driver: overlay
